name: segmentation-pytorch
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pandas>=2.2.3,<3.0.0
  - matplotlib>=3.10.1,<4.0.0
  - scikit-learn>=1.6.1,<2.0.0
  - notebook>=7.4.0,<8.0.0
  - pip
  - pip:
      - segmentation-models-pytorch>=0.4.0,<0.5.0
      - lightning>=2.5.0.post0,<3.0.0
      - albumentations==2.0.6
      - ultralytics>=8.3.94,<9.0.0
      - neptune>=1.13.0,<2.0.0
      - line-profiler-pycharm>=1.2.0,<2.0.0
      - python-dotenv>=1.1.0,<2.0.0
      - torch>=2.6.0,<3.0.0
      - torchvision>=0.21.0,<0.22.0
      - torchaudio>=2.6.0,<3.0.0 